var mongoose = require('mongoose');

var rxp_CountryBasedAISchema = mongoose.Schema({
    
    CountryBasedAI_Code                                         :Number,
    CountryBasedAI_Alert                                        :String,
    CountryBasedAI_Status                                       :Number,     
    CountryBasedAI_AI_Code                                      :Number,
    CountryBasedAI_Country_ID                                   :Number,
    CountryBasedAI_Medication_Safety_Issues                     :String,
    CountryBasedAI_Pearls_Related_Information                   :String,
    CountryBasedAI_Storage                                      :String,
    CountryBasedAI_Stability                                    :String,
    CountryBasedAI_PreparationForAdministration                 :String,

    CountryBasedAI_Administration_Rectal                        :String,
    CountryBasedAI_Administration_Oral                          :String,
    CountryBasedAI_Administration_Intravenous                   :String,
    CountryBasedAI_Administration                               :String,
    CountryBasedAI_Administration_Auricular                     :String,
    CountryBasedAI_Administration_Buccal                        :String,
    CountryBasedAI_Administration_Conjunctival                  :String,
    CountryBasedAI_Administration_Cutaneous                     :String,
    CountryBasedAI_Administration_Dental                        :String,
    CountryBasedAI_Administration_Electro_Osmosis               :String,
    CountryBasedAI_Administration_Endocervical                  :String,
    CountryBasedAI_Administration_Endosinusial                  :String,
    CountryBasedAI_Administration_Endotracheal                  :String,
    CountryBasedAI_Administration_Enteral                       :String,
    CountryBasedAI_Administration_Epidural                      :String,
    CountryBasedAI_Administration_Extra_Amniotic                :String,
    CountryBasedAI_Administration_Extracorporeal                :String,
    CountryBasedAI_Administration_Hemodialysis                  :String,
    CountryBasedAI_Administration_Infiltration                  :String,
    CountryBasedAI_Administration_Interstitial                  :String,
    CountryBasedAI_Administration_Intra_Abdominal               :String,
    CountryBasedAI_Administration_Intra_Amniotic                :String,
    CountryBasedAI_Administration_Intra_Arterial                :String,
    CountryBasedAI_Administration_Intra_Articular               :String,
    CountryBasedAI_Administration_Intrabiliary                  :String,
    CountryBasedAI_Administration_Intrabronchial                :String,
    CountryBasedAI_Administration_Intrabursal                   :String,
    CountryBasedAI_Administration_Intracardiac                  :String,
    CountryBasedAI_Administration_Intracartilaginous            :String,
    CountryBasedAI_Administration_Intracaudal                   :String,
    CountryBasedAI_Administration_Intracavernous                :String,
    CountryBasedAI_Administration_Intracavitary                 :String,
    CountryBasedAI_Administration_Intracerebral                 :String,
    CountryBasedAI_Administration_Intracisternal                :String,
    CountryBasedAI_Administration_Intracorneal                  :String,
    CountryBasedAI_Administration_Intracoronal_Dental           :String,
    
    CountryBasedAI_Administration_Intracoronary                 :String,
    CountryBasedAI_Administration_Intracorporus_Cavernosum      :String,
    CountryBasedAI_Administration_Intradermal                   :String,
    CountryBasedAI_Administration_Intradiscal                   :String,
    CountryBasedAI_Administration_Intraductal                   :String,
    CountryBasedAI_Administration_Intraduodenal                 :String,
    CountryBasedAI_Administration_Intradural                    :String,
    CountryBasedAI_Administration_Intraepidermal                :String,
    CountryBasedAI_Administration_Intraesophageal               :String,
    CountryBasedAI_Administration_Intragastric                  :String,
    CountryBasedAI_Administration_Intragingival                 :String,
    CountryBasedAI_Administration_Intraileal                    :String,
    CountryBasedAI_Administration_Intralesional                 :String,
    CountryBasedAI_Administration_Intraluminal                  :String,
    CountryBasedAI_Administration_Intralymphatic                :String,
    CountryBasedAI_Administration_Intramedullary                :String,
    CountryBasedAI_Administration_Intrameningeal                :String,
    CountryBasedAI_Administration_Intramuscular                 :String,
    CountryBasedAI_Administration_Intraocular                   :String,
    CountryBasedAI_Administration_Intraovarian                  :String,
    CountryBasedAI_Administration_Intrapericardial              :String,
    CountryBasedAI_Administration_Intraperitoneal               :String,
    CountryBasedAI_Administration_Intrapleural                  :String,
    CountryBasedAI_Administration_Intraprostatic                :String,
    CountryBasedAI_Administration_Intrapulmonary                :String,
    CountryBasedAI_Administration_Intrasinal                    :String,
    CountryBasedAI_Administration_Intraspinal                   :String,
    CountryBasedAI_Administration_Intrasynovial                 :String,
    CountryBasedAI_Administration_Intratendinous                :String,
    CountryBasedAI_Administration_Intratesticular               :String,
    CountryBasedAI_Administration_Intrathecal                   :String,
    CountryBasedAI_Administration_Intrathoracic                 :String,
    CountryBasedAI_Administration_Intratubular                  :String,
    CountryBasedAI_Administration_Intratumor                    :String,
    CountryBasedAI_Administration_Intratympanic                 :String,
    CountryBasedAI_Administration_Intrauterine                  :String,
    CountryBasedAI_Administration_Intravascular                 :String,
    CountryBasedAI_Administration_Intravenous_Bolus             :String,
    CountryBasedAI_Administration_Intravenous_Drip              :String,
    CountryBasedAI_Administration_Intraventricular              :String,
    CountryBasedAI_Administration_Intravesical                  :String,
    CountryBasedAI_Administration_Intravitreal                  :String,
    CountryBasedAI_Administration_Iontophoresis                 :String,
    CountryBasedAI_Administration_Irrigation                    :String,
    CountryBasedAI_Administration_Laryngeal                     :String,
    CountryBasedAI_Administration_Nasal                         :String,
    CountryBasedAI_Administration_Nasogastric                   :String,

    CountryBasedAI_Administration_Not_Applicable                :String,
    CountryBasedAI_Administration_Occlusive_Dressing_Technique  :String,
    CountryBasedAI_Administration_Ophthalmic                    :String,
    CountryBasedAI_Administration_Oropharyngeal                 :String,
    CountryBasedAI_Administration_Other                         :String,
    CountryBasedAI_Administration_Parenteral                    :String,
    CountryBasedAI_Administration_Percutaneous                  :String,
    CountryBasedAI_Administration_Periarticular                 :String,
    CountryBasedAI_Administration_Peridural                     :String,
    CountryBasedAI_Administration_Perineural                    :String,
    CountryBasedAI_Administration_Periodontal                   :String,
    CountryBasedAI_Administration_Respiratory                   :String,
    CountryBasedAI_Administration_Retrobulbar                   :String,
    CountryBasedAI_Administration_Soft_Tissue                   :String,
    CountryBasedAI_Administration_Subarachnoid                  :String,
    CountryBasedAI_Administration_Subconjunctival               :String,
    CountryBasedAI_Administration_Subcutaneous                  :String,
    CountryBasedAI_Administration_Sublingual                    :String,
    CountryBasedAI_Administration_Submucosal                    :String,
    CountryBasedAI_Administration_Topical                       :String,
    CountryBasedAI_Administration_Transdermal                   :String,
    CountryBasedAI_Administration_Transmucosal                  :String,
    CountryBasedAI_Administration_Transplacental                :String,
    CountryBasedAI_Administration_Transtracheal                 :String,
    CountryBasedAI_Administration_Transtympanic                 :String,
    CountryBasedAI_Administration_Unassigned                    :String,
    CountryBasedAI_Administration_Unknown                       :String,
    CountryBasedAI_Administration_Ureteral                      :String,
    CountryBasedAI_Administration_Urethral                      :String,
    CountryBasedAI_Administration_Vaginal                       :String,

},{
    toObject: { virtuals: true }
});

rxp_CountryBasedAISchema.virtual('CountryBasedAICountry', {
    ref: 'rxp_countries',
    localField: 'CountryBasedAI_Country_ID',
    foreignField: 'Country_Code',
    justOne: true // for many-to-1 relationships

});



rxp_CountryBasedAISchema.virtual('CountryBasedAIWithAI', {
    ref: 'rxp_ai',
    localField: 'CountryBasedAI_AI_Code',
    foreignField: 'AI_Code',
    justOne: false // for many-to-1 relationships

});

var CountryBasedAI_table = module.exports = mongoose.model('rxp_country_based_ai', rxp_CountryBasedAISchema);


module.exports.getLastCode = function(callback){
    
    CountryBasedAI_table.findOne({},callback).sort({CountryBasedAI_Code:-1});
}